// Comprehensive list of Binance USDT trading pairs
export const ALL_BINANCE_COINS = [
  // Top 10 by market cap
  'BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'SOLUSDT', 'XRPUSDT',
  'DOGEUSDT', 'ADAUSDT', 'TRXUSDT', 'AVAXUSDT', 'SHIBUSDT',
  // Major Layer 1s
  'DOTUSDT', 'LINKUSDT', 'MATICUSDT', 'NEARUSDT', 'ATOMUSDT',
  'ICPUSDT', 'APTUSDT', 'SUIUSDT', 'SEIUSDT', 'INJUSDT',
  'TONUSDT', 'FILUSDT', 'HBARUSDT', 'ALGOUSDT', 'FTMUSDT',
  'EGLDUSDT', 'FLOWUSDT', 'MINAUSDT', 'KSMUSDT', 'ZILUSDT',
  // DeFi
  'UNIUSDT', 'AAVEUSDT', 'MKRUSDT', 'COMPUSDT', 'SNXUSDT',
  'CRVUSDT', 'SUSHIUSDT', '1INCHUSDT', 'DYDXUSDT', 'LDOUSDT',
  'PENDLEUSDT', 'JUPUSDT', 'RAYUSDT', 'RUNEUSDT',
  // Layer 2
  'ARBUSDT', 'OPUSDT', 'STRKUSDT', 'MANTAUSDT', 'IMXUSDT',
  'METISUSDT', 'CELOUSDT',
  // AI & Data
  'FETUSDT', 'RENDERUSDT', 'GRTUSDT', 'OCEANUSDT', 'THETAUSDT',
  'ROSEUSDT', 'IOTAUSDT',
  // Gaming / Metaverse
  'AXSUSDT', 'SANDUSDT', 'MANAUSDT', 'ENJUSDT', 'GALAUSDT',
  'ILVUSDT', 'YGGUSDT', 'PIXELUSDT',
  // Meme coins
  'PEPEUSDT', 'FLOKIUSDT', 'BONKUSDT', 'WIFUSDT', 'BOMEUSDT',
  // Infrastructure
  'QNTUSDT', 'VETUSDT', 'CHZUSDT', 'APEUSDT', 'ENAUSDT',
  'WOOUSDT', 'SKLUSDT', 'CKBUSDT',
  // Exchange tokens
  'CAKEUSDT', 'GMXUSDT', 'JOEUSDT',
  // Privacy & Storage
  'XMRUSDT', 'ZECUSDT', 'ARUSDT', 'STORJUSDT',
  // Classic alts
  'LTCUSDT', 'ETCUSDT', 'BCHUSDT', 'XLMUSDT', 'EOSUSDT',
  'XTZUSDT', 'NEOUSDT', 'DASHUSDT', 'ZRXUSDT', 'BATUSDT',
  // Newer tokens
  'TIAUSDT', 'STXUSDT', 'WLDUSDT', 'PYTHUSDT', 'JTOUSDT',
  'ALTUSDT', 'MANTAUSDT', 'ONDOUSDT',
] as const;

// Remove duplicates
export const BINANCE_COINS: string[] = [...new Set(ALL_BINANCE_COINS)];

// Coin categories for organized display
export const COIN_CATEGORIES: Record<string, string[]> = {
  'Top 10': ['BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'SOLUSDT', 'XRPUSDT', 'DOGEUSDT', 'ADAUSDT', 'TRXUSDT', 'AVAXUSDT', 'SHIBUSDT'],
  'Layer 1': ['DOTUSDT', 'LINKUSDT', 'MATICUSDT', 'NEARUSDT', 'ATOMUSDT', 'ICPUSDT', 'APTUSDT', 'SUIUSDT', 'SEIUSDT', 'INJUSDT', 'TONUSDT', 'FILUSDT', 'HBARUSDT', 'ALGOUSDT', 'FTMUSDT'],
  'DeFi': ['UNIUSDT', 'AAVEUSDT', 'MKRUSDT', 'CRVUSDT', 'SUSHIUSDT', 'DYDXUSDT', 'LDOUSDT', 'PENDLEUSDT', 'JUPUSDT', 'RUNEUSDT'],
  'Layer 2': ['ARBUSDT', 'OPUSDT', 'STRKUSDT', 'MANTAUSDT', 'IMXUSDT', 'CELOUSDT'],
  'AI & Data': ['FETUSDT', 'RENDERUSDT', 'GRTUSDT', 'OCEANUSDT', 'THETAUSDT', 'ROSEUSDT'],
  'Gaming': ['AXSUSDT', 'SANDUSDT', 'MANAUSDT', 'ENJUSDT', 'GALAUSDT', 'PIXELUSDT'],
  'Meme': ['PEPEUSDT', 'FLOKIUSDT', 'BONKUSDT', 'WIFUSDT', 'BOMEUSDT'],
  'Classic': ['LTCUSDT', 'ETCUSDT', 'BCHUSDT', 'XLMUSDT', 'EOSUSDT', 'XTZUSDT'],
};
